environment:
  nodejs_version: "7"
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: Install-Product node $env:nodejs_version
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install pyinstaller"

build_script:
  - "npm install"
  - "%PYTHON%/Scripts/pyinstaller.exe app.spec"
  - "%PYTHON%/python.exe ci/prepare_release.py"

artifacts:
  - path: dist
    name: bikelab 
    type: zip
